# Generated by Django 3.0.8 on 2020-07-27 10:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MstPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=datetime.datetime(2020, 7, 27, 10, 40, 29, 424311, tzinfo=utc), verbose_name='入室日時')),
                ('exit_date', models.DateTimeField(blank=True, null=True, verbose_name='退室日時')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2020, 7, 27, 10, 40, 29, 424515, tzinfo=utc), verbose_name='更新時間')),
                ('entry_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_place', to='entry.MstPlace', verbose_name='入室場所')),
                ('exit_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_place', to='entry.MstPlace', verbose_name='退室場所')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
