# Generated by Django 3.0.8 on 2020-07-22 04:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=datetime.datetime(2020, 7, 22, 4, 26, 44, 421578, tzinfo=utc), verbose_name='入室日時')),
                ('exit_date', models.DateTimeField(default=datetime.datetime(2020, 7, 22, 4, 26, 44, 421679, tzinfo=utc), verbose_name='退室日時')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2020, 7, 22, 4, 26, 44, 421729, tzinfo=utc), verbose_name='更新時間')),
                ('entry_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_place', to='entry.MstPlace', verbose_name='入室場所')),
                ('exit_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_place', to='entry.MstPlace', verbose_name='退室場所')),
            ],
        ),
    ]
