# Generated by Django 3.0.8 on 2020-07-22 04:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 4, 31, 20, 178191, tzinfo=utc), verbose_name='入室日時'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='exit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 4, 31, 20, 178272, tzinfo=utc), verbose_name='退室日時'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='exit_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_place', to='entry.MstPlace', verbose_name='退室場所'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 4, 31, 20, 178320, tzinfo=utc), verbose_name='更新時間'),
        ),
    ]
